//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ArtGalleryEntities : DbContext
    {
        public ArtGalleryEntities()
            : base("name=ArtGalleryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArtSale> ArtSales { get; set; }
        public virtual DbSet<ArtWork> ArtWorks { get; set; }
        public virtual DbSet<Bid> Bids { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<UserInformation> UserInformations { get; set; }
    
        public virtual ObjectResult<ArtModify_Result> ArtModify(Nullable<int> artistid)
        {
            var artistidParameter = artistid.HasValue ?
                new ObjectParameter("artistid", artistid) :
                new ObjectParameter("artistid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ArtModify_Result>("ArtModify", artistidParameter);
        }
    
        public virtual ObjectResult<ArtSoldUnsold_Result> ArtSoldUnsold(Nullable<int> artistid)
        {
            var artistidParameter = artistid.HasValue ?
                new ObjectParameter("artistid", artistid) :
                new ObjectParameter("artistid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ArtSoldUnsold_Result>("ArtSoldUnsold", artistidParameter);
        }
    
        public virtual ObjectResult<BidStatus_Result> BidStatus(Nullable<int> collectorid)
        {
            var collectoridParameter = collectorid.HasValue ?
                new ObjectParameter("collectorid", collectorid) :
                new ObjectParameter("collectorid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BidStatus_Result>("BidStatus", collectoridParameter);
        }
    
        public virtual ObjectResult<HighestBid_Result> HighestBid(Nullable<int> artistid, Nullable<int> artid)
        {
            var artistidParameter = artistid.HasValue ?
                new ObjectParameter("artistid", artistid) :
                new ObjectParameter("artistid", typeof(int));
    
            var artidParameter = artid.HasValue ?
                new ObjectParameter("artid", artid) :
                new ObjectParameter("artid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HighestBid_Result>("HighestBid", artistidParameter, artidParameter);
        }
    
        public virtual ObjectResult<categoryview_Result> categoryview(Nullable<int> categoryid)
        {
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<categoryview_Result>("categoryview", categoryidParameter);
        }
    
        public virtual ObjectResult<categoryview1_Result> categoryview1(Nullable<int> categoryid)
        {
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<categoryview1_Result>("categoryview1", categoryidParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> saleid(Nullable<int> bidid)
        {
            var bididParameter = bidid.HasValue ?
                new ObjectParameter("bidid", bidid) :
                new ObjectParameter("bidid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("saleid", bididParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> saleid1(Nullable<int> bidid)
        {
            var bididParameter = bidid.HasValue ?
                new ObjectParameter("bidid", bidid) :
                new ObjectParameter("bidid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("saleid1", bididParameter);
        }
    
        public virtual ObjectResult<saleidlast_Result> saleidlast(Nullable<int> bidid)
        {
            var bididParameter = bidid.HasValue ?
                new ObjectParameter("bidid", bidid) :
                new ObjectParameter("bidid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saleidlast_Result>("saleidlast", bididParameter);
        }
    }
}
