//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtWork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArtWork()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public long ArtID { get; set; }
        public string ArtTitle { get; set; }
        public string ArtDescription { get; set; }
        public int ArtistID { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public decimal MinimumBidAmount { get; set; }
        public Nullable<decimal> CurrentBidAmount { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsSold { get; set; }
    
        public virtual UserInformation UserInformation { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
    }
}
