//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bid()
        {
            this.ArtSales = new HashSet<ArtSale>();
        }
    
        public long BidID { get; set; }
        public long ArtID { get; set; }
        public int ArtCollectorID { get; set; }
        public Nullable<long> Bidamount { get; set; }
        public Nullable<bool> IsAllocated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtSale> ArtSales { get; set; }
        public virtual ArtWork ArtWork { get; set; }
        public virtual UserInformation UserInformation { get; set; }
    }
}
