//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Credential
    {
        [Required(ErrorMessage = "Can't be empty ")]
        public int UserID { get; set; }
        [Required(ErrorMessage = "Can't be empty ")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please Select ")]
        public string UserType { get; set; }
        public string Loginerrormessage { get; set; }
        public virtual UserInformation UserInformation { get; set; }
    }
    public class UserViewModel
    {
        public Credential Credential { get; set; }
        public UserInformation UserInformation { get; set; }
    }
}
