//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long PaymentID { get; set; }
        public long SaleID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string BankName { get; set; }
        public string CardType { get; set; }
        public long CardNo { get; set; }
        public string NameOnCard { get; set; }
        public decimal Amount { get; set; }
    
        public virtual ArtSale ArtSale { get; set; }
    }
}
