//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UserInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInformation()
        {
            this.ArtWorks = new HashSet<ArtWork>();
            this.Bids = new HashSet<Bid>();
        }

        public int UserID { get; set; }
        [Required(ErrorMessage = "Please Enter First Name")]
        [DataType(DataType.Text)]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please Enter Last Name")]
        [DataType(DataType.Text)]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Can't be empty")]
        [DataType(DataType.Text)]
        public string Gender { get; set; }
        [Required(ErrorMessage = "    Please Select")]
        [DataType(DataType.Date)]
        public System.DateTime DateOfBirth { get; set; }
        [Required(ErrorMessage = "Enter Your Mail Address ")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Enter Your Phone Number")]
        public long Phone { get; set; }
        [Required(ErrorMessage = "Please Enter")]
        public string HouseNumber { get; set; }
        [Required(ErrorMessage = "Please Enter")]

        public string Street { get; set; }
        [Required(ErrorMessage = "Please Enter")]

        public string City { get; set; }
        [Required(ErrorMessage = "Please Enter")]

        public string State { get; set; }
        [Required(ErrorMessage = "Please Enter")]

        public string Country { get; set; }
        [Required(ErrorMessage = "Please Enter PinCode")]

        public long PinCode { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtWork> ArtWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual Credential Credential { get; set; }
    }
}
